---
type: entity
created: 2026-06-15
updated: 2026-06-15
sources:
  - "[itu-t-l-1470-greening-digital](../sources/itu-t-l-1470-greening-digital.qmd)"
  - "[ITU-T L.1501 (Adaptation Best Practices)](../sources/ITU-T L.1501 (Adaptation Best Practices).qmd)"
  - "[ITU-T L.1500 (Adaptation Framework)](../sources/ITU-T L.1500 (Adaptation Framework).qmd)"
tags:
  - "organization"
aliases:
  - "Intergovernmental Panel on Climate Change"
  - "IPCC"
---

## Related Entities
- [International Telecommunication Union](international-telecommunication-union.qmd)
- [UNFCCC](unfccc.qmd)

## Related Concepts
- [1.5°C scenario](../concepts/1-5c-scenario.qmd)
- [Greenhouse gas emissions](../concepts/carbon-footprint.qmd)
- [Climate change](../concepts/climate-change.qmd)
- [Climate change adaptation](../concepts/climate-change-adaptation.qmd)

## Mentions in Source
- "The trajectories, the long-term ambition and the 2015 baseline have been derived in accordance with Recommendation ITU-T L.1450 and through complementary methods in support of the 1.5°C objective described by the IPCC in its Special report: Global warming of 1.5°C and in support of the Science-based Targets (SBT) initiative."
- "Climate change refers to any change in climate over time, whether due to natural variability or as a result of human activity. The Intergovernmental Panel on Climate Change (IPCC) uses a relatively broad definition, referring to a change in the state of the climate that can be identified (e.g., using statistical tests) by changes in the mean and/or the variability of its properties and that persists for an extended period, typically decades or longer."